## 异步编程
#### 解决办法
```javascript
回调函数
事件监听
发布、订阅模式
Promise对象
```
#### Generator函数
````javascript
异步的处理方式之一"协程"，多个线程互相协作，完成异步任务
Generator函数可以交出函数的执行权。
A程序执行一半时，暂停下然后执行B程序，B程序执行完再执行A程序
````
```javascript
Generator 函数中有两个语法 yield 和 next
function * add (x) {
  let y = yield x + 2;
  return y
}
let f = add(1)
// 每次调用netx(),会返回一个对象{value: value: done: Boolean}
// value代表返回的这个阶段的值，done代表是否已经执行完毕
f.next() // 输出3
// next中带有参数传入Generator函数后，代表上个阶段异步任务的结果，被函数内的变量接受，直接返回。
f.next(2) // 输出2
```
```javascript
Generator 里可以抛出错误
function * gen(x) {
  try{
      var y = yield x + 2;
      return y;
  }catch (e){
      console.log(e)
  }
}
let f = gen(1)
f.throw('异常')
```
```javascript
Generator 请求接口
function * gen () {
	let result = yield fetch('https://didi.github.io/cube-ui/#/zh-CN/docs/scroll')
	return result
}
let g = gen()
let r = g.next()
r.value.then((data) => {
	console.log(data)
	return data.url
}).then( (data) => {
	console.log(data)
})
```
#### 异步函数async和await
```javascript
async、await其实是Generator函数的语法糖
async表示函数里有异步操作
await表示紧跟后面的表达式需要等待结果
函数前面的async的关键字，表明函数内部有异步操作，调用该函数时，会立即返回一个promise对象
```
```javascript
使用案例
function setTimeOut (ms) {
  return new Promise((resolve) => {
      setTimeout(resolve, ms)
  });
}
async function getData (x) {
  await setTimeOut(5000)
  console.log('异步执行完输出')
}
// 有时候await后面的函数有可能返回的reject，所以await函数应放在try catch 里面
```
```javascript
function setTimeOut (ms) {
  return new Promise((resolve) => {
      setTimeout(resolve, ms)
  });
}
async function getData (x) {
    try {
        await setTimeOut(5000)
       console.log('异步执行完输出')   
    } catch (e) {
        throw (e)
    }
}
```
```javascript
// 处理多个线程并发执行
let arr = [1,2,3,4,5,6,7,8]
let p = Promise.all(arr.map((item) => {
    return item + 1
}))
p.then((data) => {
    console.log(data)
})
```